### ISSUE TITLE
Missing libs for gbi32

### ISSUE THREAD

**Issue by Edouard127** [aladvs/Friday-Night-Funkin-Bot#2]
Hi, when i try to compile, it say that he cannot found the lib gbi32, do you know where this come from ?

**Comment by aladvs** [comment]
Try compiling using Visual Studio.

**Comment by aladvs** [comment]
If that doesn't work, try this :
[link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/72971f45-a384-43d1-ac24-0aa59725f772/vs2013-ultimate-microsoft-sdk-missing-from-librarypath-lnk1104-cannot-open-file-gdi32lib?forum=vssetup)

**Comment by aladvs** [comment]
If that doesn't work, just link it in your IDE's linker settings.
