### ISSUE TITLE
Can we get 768p or 720p support? Is it possible?

### ISSUE THREAD

**Issue by sabaasa** [aladvs/Friday-Night-Funkin-Bot#3]
Can we get 768p or 720p support?

**Comment by aladvs** [comment]
yes, give me a few days and it'll be done.

**Comment by sabaasa** [comment]
Thanks so much

**Comment by sabaasa** [comment]
25 days later, still waiting btw

**Comment by aladvs** [comment]
aye you still waiting? sorry man i forgot ab it i'll work on it once i get a responce

**Comment by sabaasa** [comment]
yes I'm still waiting idk why

**Comment by aladvs** [comment]
It's done.

**Comment by aladvs** [comment]
Check release 1.4.
